name: ArcadeOS
options:
  bundleIdPrefix: com.unleeshed
  deploymentTarget:
    iOS: '17.0'
targets:
  ArcadeOS:
    type: application
    platform: iOS
    sources: [ArcadeOS]
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.unleeshed.ArcadeOS
        DEVELOPMENT_TEAM: YOUR_TEAM_ID
        INFO_PLIST_FILE: ArcadeOS/Info.plist
